name: Assign MitchTeam Reviewers

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Assign MitchTeam as reviewers (only for dev -> main)
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const team = 'MitchTeam';
            const org = context.repo.owner;
            await github.rest.pulls.requestReviewers({
              owner: org,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              reviewers: [],
              team_reviewers: [team]
            });
      - name: Mark workflow as successful for other PRs
        if: github.head_ref != 'dev'
        run: echo "No team assignment needed for this PR."
