name: Assign MitchTeam Reviewers

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Assign MitchTeam as reviewers (any branch -> main)
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PERSONAL_TOKEN }}
          script: |
            // Use the team slug (all lowercase, no spaces), not the display name
            const teamSlug = 'mitchteam'; // <-- update this if your team slug is different
            const org = context.repo.owner;
            console.log('DEBUG: org =', org);
            console.log('DEBUG: teamSlug =', teamSlug);
            try {
              const result = await github.rest.pulls.requestReviewers({
                owner: org,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
                reviewers: [],
                team_reviewers: [teamSlug]
              });
              console.log('DEBUG: Reviewer assignment result:', result);
            } catch (error) {
              console.error('DEBUG: Error assigning reviewers:', error);
              throw error;
            }
